version: '3.8'

services:
  backend:
    image: newnexus/realestate-backend:latest
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=supersecretkey123
      - DYNAMO_USER_TABLE=UsersDev
      - DYNAMO_PROPERTY_TABLE=Properties

  frontend:
    image: newnexus/realestate-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped
