name: Deploy to Production

on:
  push:
    branches: [ "production" ]

jobs:
  build-production:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://your-production-app.com

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Backend (Prod)
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          newnexus/realestate-backend:production
          newnexus/realestate-backend:${{ github.sha }}

    - name: Build & Push Frontend (Prod)
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          newnexus/realestate-frontend:production
          newnexus/realestate-frontend:${{ github.sha }}
